[package]
name = "embedded-canvas"
version = "0.1.0"
authors = ["Lechev.space <dev@lechev.space>", "Lachezar Lechev"]

license = "MIT or Apache-2.0"
categories = ["embedded", "no-std"]
keywords = ["embedded-graphics", "graphics", "embedded"]
repository = "https://github.com/LechevSpace/embedded-canvas"
edition = "2021"

[dependencies]
log = "=0.4.17"

embedded-graphics = "=0.7.1"

[dev-dependencies]
embedded-graphics-simulator = "=0.3.0"
embedded-text = "=0.5.0"
env_logger = "=0.9"